title: 'LK Hospitality'
short_title: LKHEvents
description: Our objective is to create a limitless atmosphere where guest feel free to connect with each other.
baseurl:
permalink: "/:path/"
include: ['_pages']
defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
collections:
  people:
    output: true
    permalink: "/about/:path/"
  posts:
    output: true
  projects:
    output: true
    permalink: "/projects/:path/"
# tag_page_layout: tag_page
# tag_page_dir: tag
jekyll-archives:
  enabled: all
  layout: "archive"
plugins:
  - jekyll-feed
  - jekyll-archives

